### ISSUE TITLE
Strandtest Error

### ISSUE THREAD

**Issue by FusionFTW** [jgarff/rpi_ws281x#278]
Hello,

I am using a Raspberry Pi 3 to run your code in Python 2.7.

If I try to get the "Strandtest.py" running using this:

`cd rpi_ws281x/python/examples`
`sudo python2.7 strandtest.py` (or `sudo python strandtest.py`)

I always run into this Error Message:

`ImportError: No module named rpi_ws281x.rpi_ws281x`

Now when I open Strandtest.py with the Python Idle the same Error occures. In comparison if I try to run the code via "Thonny" it can't find the module "neopixel".

I already tried to install the module with pip using:

`sudo pip install rpi_ws281x`

but then it says:

`Requirement already satisfied: rpi_ws281x in /usr/local/lib/python2.7/dist-packages/rpi_ws281x-1.0.0-py2.7-linux-armv7l.egg`

Can please anyone help me? I already tried to install this with python3, but then the code by  [scottlawsonbc](https://github.com/scottlawsonbc/audio-reactive-led-strip) put out an Error with an uint_32.

**Comment by Gadgetoid** [comment]
Sorry, my bad. I had merged a PR with an erroneous import that was both unnecessary and only succeeded in certain environments: https://github.com/jgarff/rpi_ws281x/commit/755390ee0964c0ec277c0f85e4d9a599417fdedc#diff-51b66796ae181ddcd16630138da7d18b

This has now been fixed by #279

Grab the latest version of the code, or drop the offending line, and you should be good to go.
