### ISSUE TITLE
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1 on RPi 3b when 'python setup.py install'

### ISSUE THREAD

**Issue by JayJoeSeventh** [jgarff/rpi_ws281x#294]
I wanted to 'import neopixel' from anywhere, so I try to do the installation as shown. but it fails with error 'arm-linux-gnueabihf-gcc'.

Help! :(

**Comment by eloyasensio** [comment]
Hi!
I had same problem.
But I tried to follow the steps of this https://learn.adafruit.com/neopixels-on-raspberry-pi  and then I can build this without problem.
I think that solution is install "scons":
sudo apt-get update
sudo apt-get install build-essential python-dev git scons swig

**Comment by FuriosoJack** [comment]
For those that have not worked at all you have to install these packages 

`sudo apt-get install libzbar-dev libzbar0`

**Comment by KEINOS** [comment]
I think you need to install python-dev too. In order to let gcc compile the Python extensions.

```
sudo apt install python-dev
```

Sorry if it's not the case.

**Comment by tonytanjk** [comment]
I tried everything but it’s a fail

**Comment by tonytanjk** [comment]
sudo apt-get install portaudio19-dev.
Try this

**Comment by chrisdimoff** [comment]
1) Ensure SPI is enabled in `raspi_config`
2) `cd rpi_ws2811x` && run `scons`
3) try again
4) be happy?

**Comment by tlilianas** [comment]
this is what you are looking for guys : 
sudo apt install -y python python-pip libffi-dev python-backports.ssl-match-hostname
sudo pip install docker-compose

**Comment by jvanlangen** [comment]
Too bad, still:
 Building wheel for cryptography (PEP 517) ... error

**Comment by erm3nda** [comment]
@jvanlangen Your comment is insufficient.
In most of those cases, the problem comes when building a package that is required by the main package. So, you should be able to see which one is the offending package in the terminal then fix installing it's package-dev or whatever it needs.

Becase `arm-linux-gnueabihf-gcc` is a compiler, it will need always the dev packages, that includes headers for let gcc compile it.

So, run again your command, see what's the last package you can identify in the terminal, then come back.

**Comment by erm3nda** [comment]
@jvanlangen 

My fail, you refer to `cryptography` package.
Take a look at SO thread -> https://raspberrypi.stackexchange.com/questions/62364/installing-cryptography-using-pip-on-raspbian-jessie-image

**Comment by pawKer** [comment]
Just putting this out here in case it might help someone, I was getting this error because I hadn't run the `scons` command in the `rpi_ws281x` folder before running `python setup.py build` and `python setup.py install`.

**Comment by pawKer** [comment]
> Just putting this out here in case it might help someone, I was getting this error because I hadn't run the `scons` command in the `rpi_ws281x` folder before running `python setup.py build` and `python setup.py install`. Thanks @chrisdimoff !

**Comment by pawKer** [comment]
> 1. Ensure SPI is enabled in `raspi_config`
> 2. `cd rpi_ws2811x` && run `scons`
> 3. try again
> 4. be happy?

Just putting this out here in case it might help someone, this fixed it for me. I was getting the same error because I hadn't run the `scons` command in the `rpi_ws281x` folder before running `python setup.py build` and `python setup.py install`. Exactly like @chrisdimoff says above.

**Comment by maulalwi** [comment]
sudo apt install clang -y

Fixed.

**Comment by rahulshyokand** [comment]
### These Commands Fixed Similar Issue on my Rpi 3b
Note: These installations may not have any problem because some are already installed and some are not.
sudo python3 -m pip install --upgrade pip
sudo python3 -m pip install pyparsing==2.1.0
sudo python3 -m pip install pyparser==1.0
sudo apt-get install libffi-dev
sudo apt-get install libzbar-dev
sudo apt-get install clang -y

sudo apt-get install python3-dev
 sudo apt-get install libssl-dev
### Problem seems to be in cffi package
**Following command also installs cffi package which will test installation**
sudo python3 -m pip install cryptography==2.2.2
Alternativly you can try 
sudo python3 -m pip install cffi
### Here is the potential Error which gets solved 
The issue in includes of openssl.h and python.h were solved
 <#include 'Python.h'>
<#include 'openssl.h'> 
![image](https://user-images.githubusercontent.com/33034184/85941334-e8eac680-b93f-11ea-862c-5d90038b7ae8.png)

**Comment by maulalwi** [comment]
also met again with the same thing. then searching and solving

```shell
sudo apt --reinstall install libc6 libc6-dev
```

**Comment by jsxvenom** [comment]
@rahulshyokand  thank you 
I am a newbie for programming, I have same problem when try to "pip install pycurl" and show the same error.
But the problem had solved using your list of installation that you mention above.
I am new also to this github.. I dont know to quote your post.. 
thanks

**Comment by Gadgetoid** [comment]
The Python code in this repository is hopelessly obsolete, you should use the shipped Python library, source here: https://github.com/rpi-ws281x/rpi-ws281x-python

```
sudo pip install rpi_ws281x
```

**Comment by datty258** [comment]
> For those that have not worked at all you have to install these packages
> 
> `sudo apt-get install libzbar-dev libzbar0`

work for me

**Comment by ku113p** [comment]
worked for me
`sudo apt install -y libffi-dev`

**Comment by webCoderLOL** [comment]
@maulalwi Thanks! This works for me when installing rpi.gpio over Python3 virtual env.
`sudo apt install clang -y`

**Comment by manknewl** [comment]
This fixed it for me: 

sudo python3 -m pip install --upgrade pip
sudo python3 -m pip install pyparsing==2.1.0
sudo python3 -m pip install pyparser==1.0
sudo apt-get install libffi-dev
sudo apt-get install libzbar-dev
sudo apt-get install clang -y

**Comment by JulienChapron** [comment]
> This fixed it for me:
> 
> sudo python3 -m pip install --upgrade pip
> sudo python3 -m pip install pyparsing==2.1.0
> sudo python3 -m pip install pyparser==1.0
> sudo apt-get install libffi-dev
> sudo apt-get install libzbar-dev
> sudo apt-get install clang -y

and `sudo apt-get install python3-dev` on raspberry pi 4

**Comment by dmarcelino** [comment]
For me, raspberry pi 4, it was:

> sudo python3 -m pip install --upgrade pip
> sudo python3 -m pip install pyparsing==2.1.0
> sudo python3 -m pip install pyparser==1.0
> sudo apt-get install libffi-dev
> sudo apt-get install libzbar-dev
> sudo apt-get install clang -y
> and sudo apt-get install python3-dev on raspberry pi 4

Plus `sudo apt-get install build-essential`

**Comment by NuwanMadhusanka0417** [comment]
if your error shows "fatal error: python.h: no such file or directory completion terminated", you have to try this one. this fix my problem

https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory
