### ISSUE TITLE
Add Support for Bananapi m2-berry

### ISSUE THREAD

**Issue by mrbocao** [jgarff/rpi_ws281x#537]
It´s possible to add support for BananaPI M2-Berry, since the GPIO of the Banana Pi M2 Berry is declared compatible with the Raspberry Pi3 ?

**Comment by jgarff** [comment]
Sorry, but it's not very likely.  The problem isn't the GPIOs.  The project
doesn't actually use GPIO functionality since bit banging the protocol with
Linux isn't accurate enough from a timing perspective.  GPIO requires that
each bit is handled by software, and there's way too much timing jitter in
a multi-tasking OS.  That's why the project uses PWM, PCM, SPI, with DMA,
and not GPIO.  That's how the bits are clocked out to the LEDs accurately
enough to work error free.
